- name: OS upgrade for Debian
  import_tasks: apt.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Update maximum receive buffer size for Debian
  import_tasks: max-receive-buffer-size.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install qemu-guest-agent for Debian
  import_tasks: qemu-guest-agent.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install iscsi for Debian
  import_tasks: iscsi.yml
  when: ansible_facts['os_family']|lower == 'debian'
